version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: wrm-postgres
    environment:
      POSTGRES_USER: wrmuser
      POSTGRES_PASSWORD: wrmpassword
      POSTGRES_DB: wrmdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
