
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wrmdb
    username: wrmuser
    password: wrmpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
